export const devProjects = [
  {
    id: "001",
    title: "WHYCREMISI",
    type: "Plugin VST3+AU · AI · React 19 · JUCE 8",
    year: "2026",
    role: "Sviluppatore / Designer",
    desc: "Un plugin che ascolta ogni cosa che fai nel DAW, la registra, e ci parla sopra via AI. Non è un equalizzatore — è un assistente da studio che ricorda le sessioni precedenti, suggerisce mosse, e ha una faccia (BotFace: 9 stati emotivi). Costruito in C++ con JUCE 8, collegato a 6 provider AI in parallelo.",
    tags: ["C++", "JUCE 8", "REACT 19", "VST3", "AU", "OSC", "JSONL", "AI"],
  },
  {
    id: "002",
    title: "WHYPOST",
    type: "Content Automation · 15 Agenti Python · IG + TikTok + YT",
    year: "2025–26",
    role: "Architetto / Sviluppatore",
    desc: "Un sistema che produce e pubblica da solo 5–7 video al giorno su Instagram, TikTok e YouTube. Zero intervento umano, zero costi operativi. 15 agenti AI specializzati lavorano in catena: trovano argomenti, scrivono script, montano video, passano i controlli di sicurezza e pubblicano.",
    tags: ["PYTHON", "REACT", "CLAUDE", "CRONTAB", "REMOTION", "ELEVENLABS"],
  },
  {
    id: "003",
    title: "WHYCALENDAR",
    type: "App macOS · Tauri + React · Biomeccanica · WhySpidey",
    year: "2026",
    role: "Sviluppatore / Designer",
    desc: "App macOS costruita con Tauri + React. AI personal assistant con natural language scheduling e approccio biomeccanico alla gestione del tempo. Google Calendar OAuth. WhySpidey come mascotte animata pixel-art GSAP. Offline-first, completamente nativa, architettura Rust backend.",
    tags: ["TAURI", "REACT", "RUST", "AI", "GSAP", "OAUTH"],
  },
  {
    id: "004",
    title: "WHYEMUGBA",
    type: "GBA Emulator · MCP JSON-RPC · AI Control",
    year: "2026",
    role: "Sviluppatore",
    desc: "Un emulatore Game Boy Advance dove l'AI gioca al posto tuo. Claude vede lo schermo, analizza ogni frame, e preme i tasti in tempo reale. Costruito per rispondere a una domanda semplice: fino a che punto un'AI può capire un videogioco senza istruzioni?",
    tags: ["NODE.JS", "TYPESCRIPT", "WASM", "MCP", "AI", "MGBA"],
  },
  {
    id: "005",
    title: "WHYCAVALRY",
    type: "MCP Server TypeScript · File Bridge · 17 Tool · Electron",
    year: "2025",
    role: "Sviluppatore",
    desc: "Cavalry è il miglior software di motion graphics per macOS — ma non ha API. Questo progetto risolve quel problema: Claude può controllare Cavalry direttamente, creare animazioni, modificare scene, tutto via chat. Include app standalone con chatbot integrato e 7 template pronti.",
    tags: ["MCP", "TYPESCRIPT", "ELECTRON", "NODE.JS", "CAVALRY", "FILE BRIDGE"],
  },
  {
    id: "006",
    title: "RAINCAST",
    type: "App Generator · Tauri + React · AI da testo",
    year: "2025–26",
    role: "Sviluppatore",
    desc: "Generatore di app Tauri+React da descrizione testuale. Inserisci un prompt, ottieni un'applicazione funzionante con UI completa. Installato in /Applications/Raincast.app. Prototipa in minuti invece che ore.",
    tags: ["TAURI", "REACT", "AI", "CODE GEN"],
  },
  {
    id: "007",
    title: "HYPERFRAMES",
    type: "Monorepo · HeyGen API · Video Programmabili",
    year: "2025",
    role: "Sviluppatore",
    desc: "Monorepo per video programmabili con HeyGen. Bun runtime per velocità massima. Generazione automatica di video personalizzati via API HeyGen. Cartella ~/Documents/HyperFrame. Architettura monorepo con workspaces.",
    tags: ["BUN", "HEYGEN", "VIDEO", "API", "MONOREPO"],
  },
  {
    id: "008",
    title: "CLACK",
    type: "Agente Editor · Karaoke · SFX · Memoria Editoriale",
    year: "2026",
    role: "Sviluppatore",
    desc: "Un editor video AI che ha sviluppato un suo stile. Genera karaoke sincronizzato, sceglie gli effetti sonori giusti per ogni scena, e ricorda le decisioni editoriali passate per rimanere coerente. Alimenta la pipeline di WhyPost — ogni video che esce è passato da CLACK.",
    tags: ["REMOTION", "PYTHON", "KARAOKE", "AI", "ELEVENLABS"],
  },
  {
    id: "009",
    title: "SCREENPIPE",
    type: "Screen AI · MCP · Contesto Visivo Passivo",
    year: "2026",
    role: "Sviluppatore / Integrator",
    desc: "Claude che sviluppa software vede lo schermo in tempo reale — senza che tu debba fare screenshot manualmente. Screenpipe registra tutto in background e lo passa come contesto. Il risultato: meno interruzioni, più velocità, un AI che capisce davvero cosa sta succedendo.",
    tags: ["MCP", "SCREENPIPE", "AI", "MACOS", "CONTESTO"],
  },
  {
    id: "010",
    title: "WHYCREMISI V2",
    type: "Plugin VST3 AI Multi-Provider · Bridge OSC/React",
    year: "2026",
    role: "Sviluppatore",
    desc: "Evoluzione aperta di WhyCremisi: architettura modulare con supporto multi-provider AI in parallelo. Bridge OSC/React sostituibile. Repo GitHub OfficialWhyEd/VST-PlugIn-Ai. Collaborazione Carlo/Aura (Linux backend) nella fase beta originale con JUCE 7.",
    tags: ["C++", "OSC", "MULTI-AI", "VST3", "JUCE", "OPEN SOURCE"],
  },
];

export const musicProjects = [
  {
    id: "M01",
    title: "SAY I'M DIFFERENT",
    type: "Album · 25 Tracce · 53 Minuti · 2022",
    year: "2022",
    role: "Autore / Compositore / Produttore",
    desc: "Opera monumentale: 25 micro-esperienze sonore tra elettronica d'avanguardia e indie pop. Produzione, mix e mastering interamente in-the-box. Sintesi espressiva come strategia narrativa. Back In the Train e Try On Me come singoli estratti. Pubblicazione indipendente.",
    tags: ["LOGIC PRO X", "MIX", "MASTERING", "COMPOSIZIONE", "ABLETON"],
  },
  {
    id: "M02",
    title: "RAGEWINGS — STARS & WAITING",
    type: "Singoli · Collaborazione Rock/Metal",
    year: "2024–25",
    role: "Cantante Solista / Corista",
    desc: "Collaborazione rock/metal con i RAGEWINGS. Stars (feat. WhyEd, ott 2024) con videoclip Aramald Productions. Waiting for Next Friday (2025). WhyEd lascia la console e diventa pura voce interprete — produzione affidata a Carlo Figus (Sardinia Proud-Action). Maturità professionale: sa quando cedere il controllo tecnico.",
    tags: ["VOCALS", "ROCK", "METAL", "COLLAB", "CARLO FIGUS"],
  },
  {
    id: "M03",
    title: "MY LOOSING DREAMS",
    type: "Singolo Lo-Fi · 2019",
    year: "2019",
    role: "Artista Principale / Produttore",
    desc: "Texture nostalgiche, vulnerabilità e solitudine. Artwork dell'illustratore Ilya Kuvshinov. Firma poetica malinconica. Il primo progetto che ha definito l'identità sonora di WhyEd. Collaborazione FIFexclamation, Rekoj.",
    tags: ["LO-FI", "TEXTURE", "ART", "ABLETON", "KUVSHINOV"],
  },
  {
    id: "M04",
    title: "DROWNING / LIAR / ESPERA",
    type: "Singoli Solo · 2020–22",
    year: "2020–22",
    role: "Produttore / Sound Designer",
    desc: "Crescita nella programmazione ritmica e nel sound design. Dall'EDM al latin-electronic — ESPERA con influenze latine, LIAR con produzione aggressiva, Drowning con sound design cinematografico. Ogni singolo un esperimento di produzione distinto. Ricerca timbrica costante.",
    tags: ["SOUND DESIGN", "EDM", "LATIN", "ABLETON", "SOLO"],
  },
  {
    id: "M05",
    title: "ALL OVER",
    type: "Singolo · Collaborazione · 2018",
    year: "2018",
    role: "Co-produttore / Featured",
    desc: "Prima collaborazione documentata. Feat. con Semiprendebene, Drem, Hybrid. Il punto di partenza della discografia pubblica — già a 18 anni con collaborazioni multi-artista.",
    tags: ["COLLAB", "FEATURE", "2018"],
  },
];

export const projects = [...devProjects, ...musicProjects];
