export const devProjects = [
  {
    id: "001",
    title: "WHYCREMISI",
    type: "Plugin VST3+AU · AI · React 19 · JUCE 8",
    year: "2024–26",
    role: "Sviluppatore / Designer",
    desc: "Il plugin definitivo per il master channel. Non è un effetto — è un sistema cognitivo che osserva ogni azione del producer, la registra in un flight recorder JSONL append-only, parla con 6 provider AI (Anthropic, Ollama, OpenAI, OpenRouter, Groq, Gemini) e controlla il DAW via OSC. BotFace: mascotte SVG con 9 stati emotivi, sempre viva. 14/14 test automatizzati pass. Branch: heartbroken-claude.",
    tags: ["C++", "JUCE 8", "REACT 19", "VST3", "AU", "OSC", "JSONL", "AI"],
  },
  {
    id: "002",
    title: "WHYPOST",
    type: "Content Automation · 15 Agenti Python · IG + TikTok + YT",
    year: "2025–26",
    role: "Architetto / Sviluppatore",
    desc: "L'architettura più ambiziosa dell'ecosistema: 15 agenti Python specializzati che producono e pubblicano 5–7 video short-form al giorno su Instagram Reels, TikTok e YouTube Shorts. Costo operativo zero (Claude Pro headless). Pipeline: EXEL → SCRIPT → ASSET → CLACK → SAFETY → PUBLISHER. 10 cron jobs, Mission Control React full-stack, roadmap completata al 100%.",
    tags: ["PYTHON", "REACT", "CLAUDE", "CRONTAB", "REMOTION", "ELEVENLABS"],
  },
  {
    id: "003",
    title: "WHYCALENDAR",
    type: "App macOS · Tauri + React · Biomeccanica · WhySpidey",
    year: "2026",
    role: "Sviluppatore / Designer",
    desc: "App macOS costruita con Tauri + React. AI personal assistant con natural language scheduling e approccio biomeccanico alla gestione del tempo. Google Calendar OAuth. WhySpidey come mascotte animata pixel-art GSAP. Offline-first, completamente nativa, architettura Rust backend.",
    tags: ["TAURI", "REACT", "RUST", "AI", "GSAP", "OAUTH"],
  },
  {
    id: "004",
    title: "WHYEMUGBA",
    type: "GBA Emulator · MCP JSON-RPC · AI Control",
    year: "2026",
    role: "Sviluppatore",
    desc: "Emulatore Game Boy Advance dove Claude gioca al posto tuo via MCP JSON-RPC su porta :9876. Node.js + TypeScript + mGBA WASM. L'AI vede lo schermo e prende decisioni in tempo reale analizzando i frame. opencode + DeepSeek v4 come agente principale. Server su localhost:9876.",
    tags: ["NODE.JS", "TYPESCRIPT", "WASM", "MCP", "AI", "MGBA"],
  },
  {
    id: "005",
    title: "WHYCAVALRY",
    type: "MCP Server TypeScript · File Bridge · 17 Tool · Electron",
    year: "2025",
    role: "Sviluppatore",
    desc: "Connector MCP per Cavalry (motion graphics macOS). Risolve un problema fondamentale: Cavalry non ha API né AppleScript. La soluzione: file bridge elegante — il server MCP scrive JSON in ~/.whycavalry/cmd/, lo script Cavalry fa polling ed esegue, i risultati tornano in ~/.whycavalry/res/. Inclusa app Electron standalone con chatbot integrato e 7 template motion graphics.",
    tags: ["MCP", "TYPESCRIPT", "ELECTRON", "NODE.JS", "CAVALRY", "FILE BRIDGE"],
  },
  {
    id: "006",
    title: "RAINCAST",
    type: "App Generator · Tauri + React · AI da testo",
    year: "2025–26",
    role: "Sviluppatore",
    desc: "Generatore di app Tauri+React da descrizione testuale. Inserisci un prompt, ottieni un'applicazione funzionante con UI completa. Installato in /Applications/Raincast.app. Prototipa in minuti invece che ore.",
    tags: ["TAURI", "REACT", "AI", "CODE GEN"],
  },
  {
    id: "007",
    title: "HYPERFRAMES",
    type: "Monorepo · HeyGen API · Video Programmabili",
    year: "2025",
    role: "Sviluppatore",
    desc: "Monorepo per video programmabili con HeyGen. Bun runtime per velocità massima. Generazione automatica di video personalizzati via API HeyGen. Cartella ~/Documents/HyperFrame. Architettura monorepo con workspaces.",
    tags: ["BUN", "HEYGEN", "VIDEO", "API", "MONOREPO"],
  },
  {
    id: "008",
    title: "CLACK",
    type: "Agente Editor · Karaoke · SFX · Memoria Editoriale",
    year: "2026",
    role: "Sviluppatore",
    desc: "Agente editor video autonomo con memoria editoriale persistente. Genera karaoke sincronizzato, inserisce SFX contestuali, analizza viral patterns su TikTok/IG. Evoluto da semplice renderer Remotion a agente con personalità editoriale e stile coerente nel tempo.",
    tags: ["REMOTION", "PYTHON", "KARAOKE", "AI", "ELEVENLABS"],
  },
  {
    id: "009",
    title: "SCREENPIPE",
    type: "Screen AI · MCP · Contesto Visivo Passivo",
    year: "2026",
    role: "Sviluppatore / Integrator",
    desc: "Screenpipe v2.4.228 installato e integrato come MCP server. Fornisce contesto visivo passivo a Claude senza richiedere screenshot manuali. Claude vede lo schermo in tempo reale durante lo sviluppo. Installato su Monterey Intel senza problemi di compatibilità.",
    tags: ["MCP", "SCREENPIPE", "AI", "MACOS", "CONTESTO"],
  },
  {
    id: "010",
    title: "WHYCREMISI V2",
    type: "Plugin VST3 AI Multi-Provider · Bridge OSC/React",
    year: "2026",
    role: "Sviluppatore",
    desc: "Evoluzione aperta di WhyCremisi: architettura modulare con supporto multi-provider AI in parallelo. Bridge OSC/React sostituibile. Repo GitHub OfficialWhyEd/VST-PlugIn-Ai. Collaborazione Carlo/Aura (Linux backend) nella fase beta originale con JUCE 7.",
    tags: ["C++", "OSC", "MULTI-AI", "VST3", "JUCE", "OPEN SOURCE"],
  },
];

export const musicProjects = [
  {
    id: "M01",
    title: "SAY I'M DIFFERENT",
    type: "Album · 25 Tracce · 53 Minuti · 2022",
    year: "2022",
    role: "Autore / Compositore / Produttore",
    desc: "Opera monumentale: 25 micro-esperienze sonore tra elettronica d'avanguardia e indie pop. Produzione, mix e mastering interamente in-the-box. Sintesi espressiva come strategia narrativa. Back In the Train e Try On Me come singoli estratti. Pubblicazione indipendente.",
    tags: ["LOGIC PRO X", "MIX", "MASTERING", "COMPOSIZIONE", "ABLETON"],
  },
  {
    id: "M02",
    title: "RAGEWINGS — STARS & WAITING",
    type: "Singoli · Collaborazione Rock/Metal",
    year: "2024–25",
    role: "Cantante Solista / Corista",
    desc: "Collaborazione rock/metal con i RAGEWINGS. Stars (feat. WhyEd, ott 2024) con videoclip Aramald Productions. Waiting for Next Friday (2025). WhyEd lascia la console e diventa pura voce interprete — produzione affidata a Carlo Figus (Sardinia Proud-Action). Maturità professionale: sa quando cedere il controllo tecnico.",
    tags: ["VOCALS", "ROCK", "METAL", "COLLAB", "CARLO FIGUS"],
  },
  {
    id: "M03",
    title: "MY LOOSING DREAMS",
    type: "Singolo Lo-Fi · 2019",
    year: "2019",
    role: "Artista Principale / Produttore",
    desc: "Texture nostalgiche, vulnerabilità e solitudine. Artwork dell'illustratore Ilya Kuvshinov. Firma poetica malinconica. Il primo progetto che ha definito l'identità sonora di WhyEd. Collaborazione FIFexclamation, Rekoj.",
    tags: ["LO-FI", "TEXTURE", "ART", "ABLETON", "KUVSHINOV"],
  },
  {
    id: "M04",
    title: "DROWNING / LIAR / ESPERA",
    type: "Singoli Solo · 2020–22",
    year: "2020–22",
    role: "Produttore / Sound Designer",
    desc: "Crescita nella programmazione ritmica e nel sound design. Dall'EDM al latin-electronic — ESPERA con influenze latine, LIAR con produzione aggressiva, Drowning con sound design cinematografico. Ogni singolo un esperimento di produzione distinto. Ricerca timbrica costante.",
    tags: ["SOUND DESIGN", "EDM", "LATIN", "ABLETON", "SOLO"],
  },
  {
    id: "M05",
    title: "ALL OVER",
    type: "Singolo · Collaborazione · 2018",
    year: "2018",
    role: "Co-produttore / Featured",
    desc: "Prima collaborazione documentata. Feat. con Semiprendebene, Drem, Hybrid. Il punto di partenza della discografia pubblica — già a 18 anni con collaborazioni multi-artista.",
    tags: ["COLLAB", "FEATURE", "2018"],
  },
];

export const projects = [...devProjects, ...musicProjects];
