export const devProjects = [
  {
    id: "001",
    title: "WHYCREMISI",
    type: "VST3 Plugin · AI · React",
    year: "2024–26",
    role: "Developer / Designer",
    desc: "Plugin VST3 con interfaccia React e agente AI integrato. Ogni preset ha una personalità propria. BotFace mascot animato SVG+Framer Motion con 9 stati emotivi. Bridge OSC tra DSP e UI. Branch: heartbroken-claude.",
    tags: ["C++", "JUCE", "REACT", "AI", "VST3"],
  },
  {
    id: "002",
    title: "WHYPOST",
    type: "Content Automation · 15 Agents",
    year: "2025–26",
    role: "Architect / Developer",
    desc: "Pipeline autonoma di content creation per TikTok/Instagram. 15 agenti Python specializzati (EXEL, SCRIPT, CLACK, PUBLISHER...) + SwiftUI Mission Control + Claude headless. Crontab-driven, zero intervento umano.",
    tags: ["PYTHON", "SWIFTUI", "CLAUDE", "CRONTAB", "AUTOMATION"],
  },
  {
    id: "003",
    title: "WHYCALENDAR",
    type: "macOS App · Tauri + React · AI",
    year: "2026",
    role: "Developer / Designer",
    desc: "App macOS costruita con Tauri + React. AI personal assistant con natural language scheduling. Google Calendar OAuth. WhySpidey come mascotte animata. Tutto offline-first.",
    tags: ["TAURI", "REACT", "RUST", "AI", "OAUTH"],
  },
  {
    id: "004",
    title: "WHYEMUGBA",
    type: "GBA Emulator · MCP · AI Control",
    year: "2026",
    role: "Developer",
    desc: "Emulatore Game Boy Advance dove Claude gioca al posto tuo via MCP JSON-RPC su :9876. Node.js + TypeScript + mGBA WASM. L'AI vede lo schermo e prende decisioni in tempo reale. opencode + DeepSeek v4 come agente principale.",
    tags: ["NODE.JS", "TYPESCRIPT", "WASM", "MCP", "AI"],
  },
  {
    id: "005",
    title: "WHYCAVALRY",
    type: "MCP Server · Electron Bridge",
    year: "2025",
    role: "Developer",
    desc: "Connector MCP per Cavalry — bridge file-based che porta l'ecosistema Why dentro il motion graphics workflow. App Electron in /Applications/WhyCavalry.app. Comunicazione bidirezionale con il render engine.",
    tags: ["MCP", "ELECTRON", "NODE.JS", "CAVALRY"],
  },
  {
    id: "006",
    title: "RAINCAST",
    type: "App Generator · Tauri + React",
    year: "2025–26",
    role: "Developer",
    desc: "Generatore di app Tauri+React da descrizione testuale. Installato in /Applications/Raincast.app. Prende un prompt e produce un'app funzionante con UI completa.",
    tags: ["TAURI", "REACT", "AI", "CODE GEN"],
  },
  {
    id: "007",
    title: "HYPERFRAMES",
    type: "Monorepo · HeyGen · Video Programmabili",
    year: "2025",
    role: "Developer",
    desc: "Monorepo per video programmabili con HeyGen. Bun runtime. Generazione automatica di video personalizzati via API. ~/Documents/HyperFrame.",
    tags: ["BUN", "HEYGEN", "VIDEO", "API"],
  },
  {
    id: "008",
    title: "WHYCREMISI V2 / OPENCLAW",
    type: "VST3 AI Bridge · Multi-provider",
    year: "2026",
    role: "Developer",
    desc: "Plugin VST3 AI multi-provider con bridge OSC/React. Supporta più provider AI in parallelo. Evoluzione di WhyCremisi verso un'architettura aperta e modulare.",
    tags: ["C++", "OSC", "MULTI-AI", "VST3"],
  },
];

export const musicProjects = [
  {
    id: "M01",
    title: "SAY I'M DIFFERENT",
    type: "Album · 25 Tracks · 53:00",
    year: "2022",
    role: "Author / Composer / Producer",
    desc: "Opera monumentale: 25 micro-esperienze sonore tra elettronica d'avanguardia e indie pop. Produzione, mix e mastering interamente in-the-box. Sintesi espressiva come strategia narrativa.",
    tags: ["LOGIC PRO X", "MIX", "MASTER", "COMPOSITION"],
  },
  {
    id: "M02",
    title: "STARS / WAITING FOR NEXT FRIDAY",
    type: "Singles · Ragewings",
    year: "2024–25",
    role: "Lead Vocals / Chorus",
    desc: "Collaborazione rock/metal con i RAGEWINGS. WhyEd lascia la console e diventa pura voce interprete dentro un collettivo. Tracce con forte impronta live e produzione aggressiva.",
    tags: ["VOCALS", "ROCK", "METAL", "COLLAB"],
  },
  {
    id: "M03",
    title: "MY LOOSING DREAMS",
    type: "Single · Lo-Fi",
    year: "2019",
    role: "Lead Artist / Co-producer",
    desc: "Texture nostalgiche, vulnerabilità e solitudine. Artwork dell'illustratore Ilya Kuvshinov. Firma poetica malinconica. Il primo progetto che ha definito l'identità sonora.",
    tags: ["LO-FI", "TEXTURE", "ART", "ABLETON"],
  },
  {
    id: "M04",
    title: "DROWNING / LIAR / ESPERA",
    type: "Solo Singles",
    year: "2020–22",
    role: "Producer / Sound Designer",
    desc: "Crescita nella programmazione ritmica e nel sound design. Dall'EDM al latin-electronic, ricerca timbrica costante. Ogni singolo un esperimento di produzione diverso.",
    tags: ["SOUND DESIGN", "EDM", "LATIN", "ABLETON"],
  },
];

// All projects merged for certain views
export const projects = [...devProjects, ...musicProjects];
